### PR TITLE
Add rpoplpush redisfeeder

### PR DESCRIPTION
**Pull request by shoaib42**
Added `RPOPLPUSH`

- Feature

Add `RPOPLPUSH` to redis feeder. This will allow the feeder using `RPOPLPUSH` to consume for a queue and return back the right poped while atomically left push to another queue. Having `RPOPLPUSH` will allow users to simulate a scenario as described below or use a redis queue as a circular queue. A redis queue can be used as a circular queue by having the same source and destination for the `RPOPLPUSH` command.

This redis operation comes in handy when you want to send a REST request on some "ID", and then reuse it in another capacity. Say for example of a bookstore (over simplified).

Queue 1 : books to be added to catalog, gatling consumes and makes a rest call (post) to add the book to the inventory
Queue 2 : Holds books that have been added from the above operation. gatling consumes and makes a rest call to get info, search etc.

`RPOPLPUSH queue1 queue2` returns the right item from `queue1` and inserts it to the left in `queue2`

- Usage

`redisFeeder(redisPool, "mylist", "myotherlist").RPOPLPUSH();` Moves pop to `myotherlist`
`redisFeeder(redisPool, "mylist", "mylist").RPOPLPUSH();` A circular list `mylist`

* Changes
Overloaded `redisFeeder` to add another key for `RPOPLPUSH` . If LPOP, SPOP, SRANDMEMBER is used with the overloaded method `redisFeeder(clients: RedisClientPool, keySrc: String, keyDest: String)` the second key is ignored

* Tested the build with scenarios (https://gist.github.com/shoaib42/5599f774f134901bc24396f537180bf6) 
* Tested with Scala and Java for RPOPLPUSH (with circular list) and LPOP

* Redis list initial state
```
127.0.0.1:6379> RPUSH mylist "one" "two" "three" "four" "five"
(integer) 5
127.0.0.1:6379> lrange mylist 0 -1
1) "one"
2) "two"
3) "three"
4) "four"
5) "five"
127.0.0.1:6379> lrange myotherlist 0 -1
(empty list or set)
127.0.0.1:6379> 
```

* Simulation run (using rpoplpush to have a circular list)
```
================================================================================
2022-02-19 11:18:47                                          20s elapsed
---- Requests ------------------------------------------------------------------
> Global                                                   (OK=23     KO=0     )
> addComputer                                              (OK=5      KO=0     )
> addComputer Redirect 1                                   (OK=5      KO=0     )
> filterByName                                             (OK=13     KO=0     )

```

* Post run redis state
```
127.0.0.1:6379> lrange mylist 0 -1
(empty list or set)
127.0.0.1:6379> lrange myotherlist 0 -1
1) "three"
2) "four"
3) "five"
4) "one"
5) "two"
```

* Docs and tests added
Docs highlight that using RPOPLPUSH can be used to get a circular list

### CODE REVIEW

**Comment by slandelle** [comment]
Perfect!

**Comment by slandelle** [comment]
@shoaib42 Could you please sign our CLA? https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw

**Review by slandelle — APPROVED** [review]

**Comment by slandelle** [comment]
Thanks a lot!
cherry-picked

**Comment by shoaib42** [comment]
@slandelle Just wondering why the contributor says "Shoaib Khan" and not my git handle @shoaib42 :)

**Comment by slandelle** [comment]
@shoaib42 Maybe because the email you're using for your git commits (shoaib@evemeet.ca) doesn't match the one you're using for your GitHub account?

**Comment by shoaib42** [comment]
It does match, no biggie :) . I care more about that handy rotating 
redis list being in the main line so I don't have write and maintain it 
on my end :P

**Pull request closed without merging**
