### PR TITLE
Adding support for binary checks from web sockets 

### PR DESCRIPTION
**Pull request by jbank**
This has been tested. 

If you are running constant sessions with throttle rps if the web socket times out in the wsAwait.until the web socket actor is put into a bad state and doesn't recover leaving a session doing nothing for the rest of the test.

### CODE REVIEW

**Comment by jbank** [comment]
I ran all the tests locally and they have passed. I am not sure what I am missing?

**Comment by slandelle** [comment]
Hi @jbank,

Could you clean up your PR so that it only contains your own modifications, please?

Then, I wonder if having text messages and binary messaged behave the same way is right. I mean that if you're dealing with binary, there's very little chance that your content can be decoded to text, and vice-versa.

Finally, we definitively have to add some sort of CLA so we can accept eternal PRs. Stay tuned.

Thanks!

**Comment by jbank** [comment]
I am not a git wiz and I have tried to clean up this pull request but everything that I have done has had no affect. I have tried rebasing it. Can you point me in the right direction to get this cleaned up? I have had to jump through a bunch of hoops to be allowed to check this in so I would like to try and get this change submitted if possible

**Comment by slandelle** [comment]
Well, I can't hardly teach you git :(
I guess I could manage to cherry-pick your commits and then rebase for you, but you would need to first fix the merge conflicts.

Then, I do have some concerns with your pull request (see comment above). Basically, I don't think you should bridge binary and text websocket messages. WebSocket frames are types: binary, text, ping and pong (the other ones are for control) and I don't think users would expect binary frames to be automatically converted into text ones and vice versa.

**Comment by jbank** [comment]
Fair enough. How about I have another crack at it? I will create a new branch and give it a shot splitting the binary and text paths. That should clean up the new pull request. What are your thoughts?

**Comment by slandelle** [comment]
Sounds good to me.

**Comment by slandelle** [comment]
Looking forward to your PR

**Comment by slandelle** [comment]
Looking forward to your PR

**Comment by leozilla** [comment]
What is still missing for merging this? are you waiting for a "real" PR? because I can provide one, i merged it manually into gatling develop yesterday.

also do you want to wait for the next major version until merging it or will it be a feature?

**Comment by jbank** [comment]
I have spent some time trying to make the checks message type specific and I was not able to easily achieve this. If you have a clean PR I feel like it would be better to get the overall functionality into gatling and we can address the conversion between binary and text messages afterwards as the usage signature should be the same. Up to slandelle as I have had limited time to work on this feature.

**Comment by slandelle** [comment]
Will try to review next week, sorry for the delay.

**Comment by slandelle** [comment]
I'm sorry, but I think this won't get merged.

I know this is a bummer, as you put quite some effort into it, but:
* there's still a lot of effort to make this right
* the check implementation will be going under major refactoring in Gatling 3
* the WebSocket API will be completely rebooted in Gatling 3

So I really feel like all the effort required to et this feature right into Gatling 2 will go to waste.

I hope you'll understand.

**Comment by leozilla** [comment]
Looking forward to the new WebSocket API!
Is there some draft/branch to review?

**Comment by slandelle** [comment]
Not yet, we're currently setting things up. But milestones of next versions will only be available for our customers and will code only be open sourced in the stable release.

**Pull request closed without merging**
