### PR TITLE
fix GATLING_HOME detection when $0 is symlink

### PR DESCRIPTION
**Pull request by ryenus**
When gatling is launched via a symlink, e.g. `/usr/local/bin/gatling -> /opt/gatling/bin/gatling.sh` 
It fails with the following error:
> GATLING_HOME is set to /usr/local
Error: Could not find or load main class io.gatling.app.Gatling

BTW, for better cross platform compatibility, `readlink` options  `-e` or `-f` are not used, as that's GNU specific, not available in `/usr/bin/readlink` on Mac. the effect is the resolved `GATLING_HOME` could be still a symlink, but feature wise it works fine.

### CODE REVIEW

**Comment by slandelle** [comment]
@ryenus Thanks!
@notdryft Please review

**Comment by notdryft** [comment]
This modification would make the script fail for the most common case, which is running `./bin/gatling.sh` from the root directory of a fresh downloaded bundle:

```bash
$ pwd
/Users/notdryft/Playground
$ tree
.
└── bin
    └── test.sh

1 directory, 1 file
$ cat bin/test.sh
#!/bin/sh

#OLDDIR=`pwd`
#BIN_DIR=`dirname $0`
#cd "${BIN_DIR}/.." && DEFAULT_GATLING_HOME=`pwd` && cd "${OLDDIR}"
DEFAULT_GATLING_HOME=$(cd "$(dirname "$(readlink -n "$0")")/.."; pwd)

GATLING_HOME="${GATLING_HOME:=${DEFAULT_GATLING_HOME}}"

echo "GATLING_HOME is set to ${GATLING_HOME}"
$ ./bin/test.sh
$ ln -s /Users/notdryft/Playground/bin/test.sh /usr/local/bin/test.sh
$ test.sh
GATLING_HOME is set to /Users/notdryft/Playground
```

So, maybe detect the nature of the link and use readlink or the former method depending of the result?

**Comment by ryenus** [comment]
@notdryft is right, sadly `readlink -n ./bin/test.sh` never print anything, be it `/usr/bin/readlink` on Mac, or GNU `readlink` from coreutils.

Maybe the solution is to [resort to `perl`][1] first, then fallback to gnu `readlink`?

[1]: http://stackoverflow.com/a/24572274/537554

**Comment by slandelle** [comment]
@notdryft please review again

**Comment by slandelle** [comment]
I'm sorry, but I'd rather not take the risk of breaking something that works for the sake of supporting a rare and non standard usage.

**Pull request closed without merging**
