### PR TITLE
Update GatlingPropertiesBuilder.scala

### PR DESCRIPTION
**Pull request by gauravBINdas**
Change : import scala.collection.mutable._
Previously : import scala.collection.mutable

Fixed Issue : 
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Object scala.collection.mutable.Map$.empty()'
at io.gatling.core.config.GatlingPropertiesBuilder.<init>(GatlingPropertiesBuilder.scala:25)
at io.gatling.app.cli.ArgsParser.<init>(ArgsParser.scala:26)
at io.gatling.app.Gatling$.fromArgs(Gatling.scala:44)
at io.gatling.app.Gatling$.main(Gatling.scala:37)
at io.gatling.app.Gatling.main(Gatling.scala)

### CODE REVIEW

**Comment by slandelle** [comment]
This looks wrong to me. I suspect your issue is because you're not using the correct Scala version. Gatling currently requires Scala 2.13 and is not compatible with 2.12 or 3.

**Comment by gauravBINdas** [comment]
@slandelle , Initially I was thinking the same but even after setting the scala version: 2.13.6 , I faced the same exception.
To resolve the exception , I think we need to import the Map trait that's why added   import scala.collection.mutable._

**Comment by slandelle** [comment]
Could you please provide a way to reproduce your original issue?

**Comment by slandelle** [comment]
Any update on this?

**Comment by gauravBINdas** [comment]
The issue is fixed.Please discard the PR. You were right about the scala
version.gatling/lib folder was corrupted because of other scala version jar
files

**Pull request closed without merging**
