### PR TITLE
Core: Put user counters at the end to see them without scrolling when there are a lot of different requests

### PR DESCRIPTION
**Pull request by henri-tremblay**

### CODE REVIEW

**Comment by slandelle** [comment]
Thanks, will give it a try this week.

**Comment by slandelle** [comment]
Mmm, actually, when there's lots of requests, at some point you'd have to scroll anyway, and your change makes it harder to see how users are advancing.
IMO, it makes more sense to leave as is.

@notdryft WDYT?

**Comment by slandelle** [comment]
Me stupid, missing your point.

**Comment by slandelle** [comment]
Cherry-picked, thanks man!

**Comment by henri-tremblay** [comment]
Thanks!

**Pull request closed without merging**
