### PR TITLE
Use the correct request name in the assertion documentation

### PR DESCRIPTION
**Pull request by leozilla**
Just a minor documentation fix for a part of the docs which I contributed a couple of weeks ago.

See: https://gatling.io/docs/current/general/assertions
The request name in the text does not match the code example

### CODE REVIEW

**Comment by Neoware** [comment]
Hey! Thanks for spotting that error. 

Your PR doesn't concern the websocket part of the assertion documentation. 

Furthermore I think that the naming in this part of the documentation is very confusing. "Search" is considered a group and a request depending of the context, and the same name is used for the "Index" request inside and outside the group. If it was the case in a simulation, that would work, but I don't think that's the best way of explaining that feature. Maybe we could just change the name to something like:
- Search as a group, and Index as a request inside that group.
- Home as a request outside of a group.

Is it possible for you to fix that ?

If you are okay with these modifications, don't forget to also change the https://gatling.io/docs/current/general/assertions/#putting-it-all-together part of the documentation! 

Thanks in advance!

**Comment by Neoware** [comment]
@leozilla do you agree on these suggestions ?

**Comment by leozilla** [comment]
@Neoware yes I agree, sorry I totally forgot to adjust it, will do it this week

**Comment by leozilla** [comment]
@Neoware I updated the PR, I hope I understood and implemented your suggestions correctly

**Comment by slandelle** [comment]
@Neoware PTAL

**Comment by Neoware** [comment]
hey, sorry for the delay !

Could you add a setUp example with the Home request in the Putting it all together?

Once it's finished could you squash your commits in a single one ?

Thanks in advance ! :)

**Comment by slandelle** [comment]
Sorry for the very long wait. I've cleaned up the names, thanks for reporting!

**Pull request closed without merging**
