### PR TITLE
improve HTML report print view

### LINKED ISSUE #4353: HTML Report: Improve 'Print to PDF' layout/view
#### Current Situation

It is almost impossible to export the HTML report to a multi-page PDF with the current CSS configuration. The PDF always contains a single page with the scrollbars visible. See attached screenshot.

no-media-query

#### Solution Proposal

Modern browsers support a media query called: `@media print` with which the CSS can be customized when a HTML page printed (e.g., when a user clicks 'Print to PDF' in the browser). 

I have experimented a little bit and with the main CSS file: [https://github.com/gatling/gatling/tree/main/gatling-charts/src/main/resources/io/gatling/charts/assets/style/style.css](https://github.com/gatling/gatling/tree/main/gatling-charts/src/main/resources/io/gatling/charts/assets/style/style.css) and have added the following print media query. 

##### Additional CSS

```css
@media print {
	.nav {
		display: none;
	}

	.cadre {
		overflow-y: unset;
	}

	.content-in {
		overflow-x: unset;
	}
}
```

It hides the sidebar navigation and removes the horizontal and vertical scrollbars, allowing the content to flow over multiple pages. 

with-media-query

I'd be happy to contribute this as a PR, if others think this might be a valuable addition.

### PR DESCRIPTION
**Pull request by meck93**
closes #4353

- [x] improves the HTML report print view
- [x] fix *style.css* formatting mistakes

### CODE REVIEW

**Comment by slandelle** [comment]
@franciscotco Please review

**Comment by slandelle** [comment]
@meck93 Thanks! Could you please sign our [CLA](https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw)?

**Comment by meck93** [comment]
> @meck93 Thanks! Could you please sign our [CLA](https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw)?

Done!

**Review by franciscotco — APPROVED** [review]

**Comment by slandelle** [comment]
cherry-picked

Thanks a lot!

**Pull request closed without merging**
