### PR TITLE
Add method 'runForResults' to run Gatling and get run result

### PR DESCRIPTION
**Pull request by mperever**
Hello,

The main idea is provide functionality to get gatling run result for following processing. Gatling saves an execution results and simulation log in autogenerated folder. There is no way to get autogeneraed value, but thvaule is stored in 'RunResult'.
I suggest adding a method that returns the result of gatling run.

Thanks
Maksym

### CODE REVIEW

**Comment by slandelle** [comment]
What' the purpose of this change?

**Comment by mperever** [comment]
The purpose is to get Gatling run result object after execution, instead of execution status code (int).
https://github.com/gatling/gatling/blob/master/gatling-app/src/main/scala/io/gatling/app/RunResult.scala
https://github.com/gatling/gatling/blob/master/gatling-app/src/main/scala/io/gatling/app/cli/StatusCode.scala

RunResult allows to implement other features for Gatling.
In my project, I need use LogFileReader to get some stats, but LogFileReader requires RunResult.
https://github.com/gatling/gatling/blob/master/gatling-charts/src/main/scala/io/gatling/charts/stats/LogFileReader.scala

Furthermore I found that a lot of people is asking how to get auto generated folder name with log file.
simulation-xxxxxx\simulation.log

**Comment by slandelle** [comment]
So basically, I have the feeling the change you suggest helps you with some custom launcher/integration that you have but doesn't benefit Gatling, ie the official components that we provide.

**Comment by mperever** [comment]
Yes, but in general it's good to have an opportunity to get RunResult to integrate Gatling with other systems.

**Comment by slandelle** [comment]
Sorry, but please understand that we manage a large ecosystem with lots of components, from open-source ones to commercial products. We have nothing to gain from opening this, and on the contrary it would bring more complexity when/if we want to change things.
Basically, what you suggest is not a feature, and I'll have to turn it down.
I hope you'll understand.

**Pull request closed without merging**
