### PR TITLE
HTTP: Make Http Protocol localAddress take an Expression

### PR DESCRIPTION
**Pull request by pdalpra**

### CODE REVIEW

**Comment by slandelle** [comment]
I wonder if you could reduce allocations here.

**Comment by pdalpra** [comment]
We could easily make them function values instead of methods.

**Comment by slandelle** [comment]
Higher order functions wouldn't reduce allocation :)

**Comment by pdalpra** [comment]
Do you prefer that i switch back to the previous form and drop `ExpressionRequestConfigurator` ?

**Comment by slandelle** [comment]
Yeah. Let's do that in 2 steps: first provide the feature, then let's see if we can improve.

**Comment by pdalpra** [comment]
Updated the PR to include only the feature.

**Comment by slandelle** [comment]
Thanks mate!

**Comment by pdalpra** [comment]
You're welcome :)

**Pull request merged**
