### PR TITLE
Recorder: Split password into keyStorePassword and keyManagerFactoryPassword

### PR DESCRIPTION
**Pull request by ggsjyoon**
in SslServerContext, ConfigKeys, RecorderConfiguration, and recorder-defaults.conf.

### CODE REVIEW

**Comment by ggsjyoon** [comment]
I'm not sure why PaceSpec keeps timing out during CI, could it be a latency issue?

**Comment by slandelle** [comment]
Thanks! I'm off atm, I'll merge later this week.

**Comment by slandelle** [comment]
PaceSpec fails because some tests (Akka testkit based) expect some timings and Travis hosts frequently experience pauses/slowdowns.

**Comment by slandelle** [comment]
I asked the original reporter for more information. I'd like to be sure that having different password isn't a very rare usage.

Then, this new property should be exposed in the GUI. And we'd have to define rules, eg when left blank, we should maybe fall back to the current behavior.

**Comment by ggsjyoon** [comment]
I agree with you

**Comment by slandelle** [comment]
This PR is broken and ships unrelated commits.
And we still don't know if this is useful for anyone.

Closing for now, will reopen if it makes sense.

**Pull request closed without merging**
