### PR TITLE
Update default branch in documentation to 'main'.

### LINKED ISSUE #4092: edit link on https://gatling.io/docs/current/ does not work
The edit link on https://gatling.io/docs/current/ goes to https://github.com/gatling/gatling/edit/master/src/sphinx/index.rst, which is a 404. It should probably go to https://github.com/gatling/gatling/edit/main/src/sphinx/index.rst instead.

### PR DESCRIPTION
**Pull request by reftel**
Fixes #4092

### CODE REVIEW

**Comment by Isammoc** [comment]
Thank you for this PR and the raised issue! :confetti_ball: 
Indeed, we ( i, me and myself) forgot to update the documentation when I changed the default branch.

As usual in this repository, I won't directly merge your contribution.

But can you sign our [CLA](https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw) as I will be able to cherry-pick your contribution?

(Note that I will add other places where I missed the update as well)

**Comment by slandelle** [comment]
@reftel gentle ping regarding the CLA. We have a release coming vey soon and would like to merge your contribution.

**Comment by reftel** [comment]
CLA signed.

**Comment by Isammoc** [comment]
Thank you!
Merged with ea97af02f5ba6d46f61937269a83cd2866f74292

**Pull request closed without merging**
