### PR TITLE
Fix malformed json assertion results file, close #3192

### LINKED ISSUE #3192: Assertions json report file is malformed
The value of attribute actualValue is missing an opening '[' causing the json to be malformed.

e.g.
 "actualValue": 768.0]

### PR DESCRIPTION
**Pull request by macox**
Adding a missing '[' to the value of the actualValue attribute

### CODE REVIEW

**Comment by macox** [comment]
Fixes #3192

**Comment by slandelle** [comment]
cherry-picked, thanks!

**Comment by macox** [comment]
@slandelle any chance this can be included in 2.3.1?

**Comment by slandelle** [comment]
Actually, this was shipped in 2.2.4

**Pull request closed without merging**
