### PR TITLE
Count responses and durations in the correct range, close #4435

### LINKED ISSUE #4435: Reports: Responses and durations with the same value as higherBound are not counted correctly.
The environment	
	gatling 3.9.5
	windows 10
	OpenJDK 17

Using latest gatling-sbt-plugin-demo to generate HTML report with simulation.log with 1200ms response time and 1200ms duration.	
Unzip the attached file timerangetest-1111.zip, place it under target/gatling and execute the following.	
 Gatling/generateReport timerangetest-1111	
	
[timerangetest-1111.zip](https://github.com/gatling/gatling/files/11814191/timerangetest-1111.zip)

Requests and durations are counted as "800 ms <= t < 1200 ms" in the console and "t>= 800ms t<1200ms" in the chart (Group Duration Ranges, Response Time Range).	
It is correct to count t > 1200ms.

### PR DESCRIPTION
**Pull request by kudoueiji**

### CODE REVIEW

**Comment by slandelle** [comment]
Thanks a lot!

Could you please [sign our CLA](https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw/edit) so  can merge?

**Comment by kudoueiji** [comment]
We signed the CLA in 2017.
We have made the following pull requests in the past.
https://github.com/gatling/gatling/pull/3263
https://github.com/gatling/gatling/pull/3257

Need to sign again?

**Comment by slandelle** [comment]
@kudoueiji It seems we failed to properly enforce signing the CLA back then.

**Comment by kudoueiji** [comment]
I just sent the emails we exchanged when we signed the GCA to your email address.
Please check your email above.

**Comment by slandelle** [comment]
@kudoueiji My bad, sorry, I was only looking in the individual agreements, not the company-wide ones.

**Comment by slandelle** [comment]
cherry-picked, thanks a lot!

**Pull request closed without merging**
