### PR TITLE
Recorder: implement headless frontend

### PR DESCRIPTION
**Pull request by pdalpra**

### CODE REVIEW

**Comment by slandelle** [comment]
Looks great! Doc?

**Comment by pdalpra** [comment]
On it !

**Comment by pdalpra** [comment]
I added a section to the Recorder's documentation on the headless mode.

**Comment by slandelle** [comment]
Awesome!

**Comment by slandelle** [comment]
Ping @alxndrsn

**Comment by slandelle** [comment]
Ping @cprice404

**Comment by alxndrsn** [comment]
Nice one :-)  Keep up the good work.

**Comment by cprice404** [comment]
awesome!  thx for the heads up.

**Pull request merged**
