### PR TITLE
feat: added svg to the ignore static resource list

### PR DESCRIPTION
**Pull request by arturbdr**
Could we, also, ignore the svg request as part of the static resource list?

### CODE REVIEW

**Comment by slandelle** [comment]
Makes sense. Thanks!

**Comment by slandelle** [comment]
cherry-picked

Thanks!

**Comment by slandelle** [comment]
@arturbdr  Gatling 3.9.1 is out.

**Comment by arturbdr** [comment]
Thank you @slandelle!

**Pull request closed without merging**
