### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by micheljung**
First draft, you might want to improve some things, like:

* Replace PNG icons like "sortable", "roue" and "temps" with an SVG to allow
  styling
* Revise "Try Gating Enterprise"

Tested on Google Chrome. The setting was stored even when opening another
report with a different path.

Fixes GH-4281

image

### CODE REVIEW

**Comment by slandelle** [comment]
@micheljung Looks grat, thanks!
@gpoulet Could you please review?

**Comment by slandelle** [comment]
@micheljung Could you please sign our [CLA](https://docs.google.com/forms/d/1hbpxVqJ5hIYYJuOjOyOzub9fJFGFGvvfnB5w5LCWdUw)?

**Review by gpoulet — APPROVED** [review]
LGTM!

Thank you 👍

**Comment by micheljung** [comment]
@slandelle signed

**Pull request closed without merging**
