### PR TITLE
fix: url in third_parties.md

### PR DESCRIPTION
**Pull request by Maksimall89**

### CODE REVIEW

**Comment by slandelle** [comment]
Thanks, but this has already been fixed in main branch is this commit: https://github.com/gatling/gatling-private/commit/72895b79f4cebf641698d1ba44678e88f671c059 and the fix is already visible online: https://gatling.io/docs/gatling/reference/current/extensions/third_parties/.

**Comment by Maksimall89** [comment]
Unfortunately, I can't see the commit from Gatling private. Also, I still see this bug.

изображение

**Comment by slandelle** [comment]
> Unfortunately, I can't see the commit from Gatling private.

Sorry. Fixed link to public commit in my previous message.

> Also, I still see this bug.

Ha, you're correct. We'll publish the fix during the next release.

**Comment by Maksimall89** [comment]
ok, thx

**Pull request closed without merging**
