### PR TITLE
Tracker Destination can by specified independent from replyTo Destination

### PR DESCRIPTION
**Pull request by LukasHavemann**
Hello, 

we have a complex JMS setup in which we need to specify the tracker destination independent from the replyTo destination.

Best regards
Lukas

### CODE REVIEW

**Comment by slandelle** [comment]
Sorry, I don't get it. Could you please explain your use case, how the current features don't let you do that and how you're trying to solve it?

**Comment by LukasHavemann** [comment]
Our use case looks like this:

System A is sending a inital request to system B.
System B answers the request and is waiting for a confirmation from system A. 
System A sends the confirmation  to system B. 
System B sends a notfication to system C. 

We now want to loadtest system B and want to measure the runtime between the inital request and the notification to system C.

So we use Gatling to initiate the request and to receive the notification to system C.  We have a Stub   that receives the response from System B and sends the confirmation. 

Thats why we need to specify the replyTo independently from the queue where Gatling is listing for the response. If our use case were a simple request/response scenario we wouldn't use a async protocol like JMS.

**Comment by LukasHavemann** [comment]
For clarification: our very simplified testsetup looks like this:

lasttest

**Comment by LukasHavemann** [comment]
I am new to scala and sbt. How can I build a new release of gatling with sbt locally?

**Comment by LukasHavemann** [comment]
@slandelle any updates on this pr?

**Comment by slandelle** [comment]
Can’t you have Gatling deal with both initial request and confirmation and measure overall time with a group ?

**Comment by LukasHavemann** [comment]
I don't want to hesitate you with our concrete setup and all the details. To summarize: with a lot of effort, it may be possible to replicate the behaviour of teststub T in gatling, but that's not an option for us.

Decoupling, asynchronicity and routing are big advantages of async messaging systems. I think a load testing tool like gatling, should support these concepts and shouldn't limit the user to simple request/response scenarios. I can understand that you want to keep the API small, but this small change would make gatling much more useful in a complex MQ-setups.

**Comment by slandelle** [comment]
Again, I don't get why you can't do:

```scala
group("total") {
exec(jms("initialRequest").requestReply.replyDestination(queue("queueB"))
.exec(jms("confirmation").requestReply.replyDestination(queue("queueC"))
}
```

The tracker is an implementation detail and it doesn't make sense to turn it into an API.

**Comment by LukasHavemann** [comment]
The generation of the confirmation message is relatively CPU expensive. If we would use a group, we wouldn't be able to scale horizontally, and we need to scale the machine running gatling vertically.

It is only an internal implementation detail, if you limit the user to simple request/response scenarios. If you embrace all the use cases of an async messaging system, it isn't. Other jms load testing tools allow the user to specify the listener (tracker) destination independently from the replyTo destination. But these tools are not as fast and good as gatling.

**Comment by slandelle** [comment]
Could you please address comments and add documentation (https://github.com/gatling/gatling/blob/master/src/sphinx/jms.rst)?

**Comment by slandelle** [comment]
Oups, forgot to request changes so they were still pending.

**Comment by opensource21** [comment]
I fixed the conflicts and use your comments to improve the code. Furthermore I added the documentation. See #3428 . Is think we could close this PR.

**Comment by slandelle** [comment]
@opensource21 Thanks! Having a look at your PR right away!

**Pull request closed without merging**
