### PR TITLE
Fix SBT Plugin documentation

### PR DESCRIPTION
**Pull request by pdalpra**

### CODE REVIEW

**Comment by pdalpra** [comment]
@slandelle should this close #2816 (again) ?

**Comment by slandelle** [comment]
Is there still a point in having gatling-it?

**Comment by pdalpra** [comment]
I think there is: you may want to split short lived simulations ("unit" tests) and long-lived ones (load tests) so having the ability to have separate folders seems useful IMHO

**Comment by slandelle** [comment]
LGTM, thanks!

**Pull request merged**
