### PR TITLE
Provide a lazy, batched CSV reader

### PR DESCRIPTION
**Pull request by reikje**
see https://github.com/gatling/gatling/issues/2602

Currently csv files are loaded eagerly which is a problem when the files are very big. This `Feeder` processes portions of the csv file on demand in batches. When creating, you can specify batch size and how often you want to move to the next batch.

### CODE REVIEW

**Comment by slandelle** [comment]
Hi! Thanks for contributing!

Actually, I wonder if it really makes sense to implement lazy file based feeders and support any strategy other than queue.

Also, my concern with the implementation you suggest is the blocking that happens when fetching the next batch. Next batch(es) could be fetch in the background, and could be triggered/paused by some watermarks.

Finally, one of the problem with Feeder footprint is that most boil down to `Array[Map[String, String]]`. We could change some implementations in Gatling 3 so that we only compute the `Map`s when pulling data.
One game changer could also be Java 9 Compact Strings coming, as `String` will no longer be backed by an UTF-16 char array.

**Comment by reikje** [comment]
> .. the blocking that happens when fetching the next batch

It's actually not blocking. For one single call to `hasNext` the condition `if (itemsUsed.incrementAndGet() == minUsedItemsPerBatch) {` will evaluate to `true` and this Thread will go on and fetch the next batch. While it is doing this, subsequent requests will still run on the old batch - all until the updating Thread has updated `currentBatch`.

> .. support any strategy other than queue

The strategy is only applied onto the items in the current batch (see `BatchedFeederBuilderSpec`). I agree, Queue would be the only strategy that makes sense for the whole dataset. It's currently not implemented like this.

**Comment by slandelle** [comment]
> It's actually not blocking

Let me correct myself: the blocking happens when the underlying `InputStream`'s buffer runs out so it has to fetch from disk again: 

```
SeparatedValuesParser.stream(res.inputStream, CommaSeparator, quoteChar, escapeChar)
```

**Comment by reikje** [comment]
I see. How is `hasNext` and `next` used currently? Is there a some synchronisation/lock that allows only 1 thread at the same time? I can't see how it would be thread-safe otherwise. In that case your suggestion to eagerly fetch the next batch would be beneficial. Let me know if I should adapt the pull request to do that.

**Comment by slandelle** [comment]
See `FeedBuilder` sources: each Feeder instance is bound to a single Actor, so Iterator processing is threadsafe and sequential. And indeed, your AtomicInteger/AtomicLong are useless.

**Comment by reikje** [comment]
Yes, I was thinking this code was executed in parallel. How would you implement the background loading in that case?

**Comment by reikje** [comment]
@slandelle how can we move forward with this PR, it's really something we wanna use here :) any suggestion on the background loading (since it's an Actor)?

**Comment by slandelle** [comment]
I guess background loading can come in a second time.

But there are several things I'm not fond of.

* `minUsedItemsPerBatch`: I fail to see why users would want to use that, except for working around some limitations of this implementation. Let's just read again once batch is depleted.
* you're leaking a file descriptor: the underlying `InputStream` is never closed
* strategies are broken. They should behave in a similar fashion as the non batched versions:
  * `circular` should open a new InputStream and start reading the file over again
  * `shuffle` should pick a random entry in the batch, but should stop when all data is depleted.
  * `random` should pick a random entry in the batch, but start reading the file over again like `circular`

**Comment by reikje** [comment]
* `minUsedItemsPerBatch`: let's say we didn't have this and ".. read again once the batch is depleted". What is your definition of "depleted"? That I have exhausted my batch records via the `FeederStrategy`? `random` and `circular` never exhaust (`hasNext` will always be true). `minUsedItemsPerBatch` simply defines at which point the next batch should be loaded regardless of the selected `FeederStrategy`. So for instance, a user may chose to get 1000 items from the current batch of size 100 using the `Circular` strategy and then move on to the next batch.

* leak: will fix

* broken strategies: when the batch is initialised in `def nextBatch()` it delegates to the existing strategies, so it should work very much the same way (per batch strategy). Sorry I [don't see](https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/feeder/FeederStrategy.scala) where `circular` or `random` reads the underlaying file again. It looks like the only difference are the access patterns to the given `records: IndexedSeq[Record[T]]`.

**Comment by slandelle** [comment]
You're focused on the implementation and reusing the current implementation strategies. There's a good chance we'll have to change them.

As a user, I don't care if the same piece of code is involved for batch and non-batched or not. What I care about is behavior. Having a circular behavior is completely unrelated to batch/lazy vs full/eager loading.

**Comment by reikje** [comment]
Yes `circular` and `queue` could easily work the same way between batched and non-batched. `shuffle` and `random` are not as straight-forward, or how would you implement these when you have 1M entries and 100 batches of 10.000 items?

**Comment by slandelle** [comment]
> how would you implement these when you have 1M entries and 100 batches of 10.000 items

I think it would be fine if both would shuffle the batch when it's being loaded.
On depletion,`random` would jump back to the beginning of the file while `shuffle` would exit, just like `queue`.

**Comment by slandelle** [comment]
@reikje Sorry for the very long delay. I just pushed my own take on batched feeders, inspired by your version: ccac0dfc18a4f48281670cc1c7fc4f3a0076cdfd

I didn't try to handle possible hiccups when reading next batch, will have to measure.
Feedback welcome.

Thanks again!

**Pull request closed without merging**
